import Head from 'next/head';
import Aos from 'aos';
import { useEffect } from 'react';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { Subscribe } from '../components/Subscribe';
import 'aos/dist/aos.css';
import { HeroError } from '../components/Hero404';

export default function About({ posts }) {
  useEffect(() => {
    Aos.init({ duration: 1500 });
  }, []);
  return (
    <div>
      <Head>
        <title>BMS.Blog | Técnologia em um click!</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Header />
        <HeroError />
        <Subscribe />
        <Footer />
      </main>
    </div>
  );
}